### ISSUE TITLE
Is this updated?

### ISSUE THREAD

**Issue by shubhrampandey** [jbarton311/coronavirus-analysis#1]
I am not sure if the data is updated for 23rd march and now JHU removed recovered cases are you still providing recovered cases?

**Comment by jbarton311** [comment]
Hi @shubhrampandey,

I updated yesterday evening and removed recovered cases. I am still waiting for JHU to publish enhanced US county-level data. Right now, US is aggregating at the country level.

**Comment by shubhrampandey** [comment]
Ok Thanks
